name: Build containers for a specific branch
on:
  push:
    branches:
      - windows-image
  workflow_dispatch:
    inputs:
      version:
        description: Version of Fluent Bit to build, commit, branch, etc. The container image will be ghcr.io/fluent/fluent-bit/test/<this value>.
        required: true
        default: master
jobs:
  build-branch-containers:
    uses: nordcloud/fluent-bit/.github/workflows/call-build-images.yaml@master
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.version }}
      registry: ghcr.io
      username: ${{ github.actor }}
      image: ${{ github.repository }}/fluentbit/${{ github.event.inputs.version }}
      # unstable: ${{ github.event.inputs.version }}
    secrets:
      token: "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" #${{ secrets.GITHUB_TOKEN }} #PAT
